### ISSUE TITLE
Error when I load the .jar

### ISSUE THREAD

**Issue by OMarcoGPO** [TeamVK/PAPI-Enchantment#5] opened 2024-08-13 10:02 UTC
Hi! Before I explain the error, I really didn't know if I had to put the .jar on \plugins or \plugins\placeholderapi\expansions , anyway, I tried the two fo them and I get errors on the twice cases. 

Using paper 1.21
Using PlaceholderAPI 2.11.6

When I put .jar on \plugins:
Error: https://imgur.com/a/0STJZAd

When I put .jar on \plugins\placeholderapi\expansions
Error: https://imgur.com/a/0STJZAd

**Comment by vk2gpz** [comment] 2024-08-13 23:09
try 1.3.1

**Comment by OMarcoGPO** [comment] 2024-08-14 09:47
It didn't work saddly
![image](https://github.com/user-attachments/assets/008df8f7-81f5-4fb2-a77b-4e596b7bea10)

**Comment by vk2gpz** [comment] 2024-08-14 11:05
I'm closing this since I do not have time to deal with this kind of trolling.

**Closed as completed** 2024-08-14 11:05 UTC

**Comment by OMarcoGPO** [comment] 2024-08-14 13:03
Hi, I don't understand what type of trolling you think is this. I know that you did the 1.3.1 yesterday for the 1.21, but something still not working.

The error that I sent you was when I loaded on \plugins (I undestand that is the reason that you think about a troll, I understand)

As I said at first, I really didn´t know that I should put the .jar on \plugins\placeholderapi\expansions
I know now because I created a 1.20.4 temporarily server for testing it and it worked.
So the error its probably related to the 1.21 version

The actual error should be this so:
![image](https://github.com/user-attachments/assets/b2d24c24-0879-4b0e-b14d-ae2c20827cb2)

If you don't have time right now, I guess I can wait, thats okay

Should I write the PlaceholderAPI directly maybe? They told me to write you yesterday

Hope that everything is understandable

**Comment by vk2gpz** [comment] 2024-08-24 11:08
The issue you're experiencing is caused by the class loading process of PlaceholderAPI.  You should check whether this happens with any version of PlaceholderAPI or only with the latest one.

**Comment by vk2gpz** [comment] 2024-08-27 00:21
I submitted a pull request (https://github.com/PlaceholderAPI/PlaceholderAPI/pull/1081) to resolve this issue.  It's up to PlaceholderAPI team to accept or reject this pull request.  
If you cannot wait, then you can apply the patch yourself and build the fixed version yourself.
